### PR TITLE
Added few more emojis

### PR DESCRIPTION
**Pull request by suyesh**
Couple of more Emojis.

### CODE REVIEW

**Comment by m1foley** [comment]
Thanks for the contribution!

1. Can you add comments for all of the emojis like you did for the last one?
2. I've never heard of using 💉 as "prick". Is that well known?

**Comment by suyesh** [comment]
Hi, 

Added comments. Not sure if Prick is used often but at my work it does :)

**Comment by m1foley** [comment]
Let's leave out 💉 because its usage is typically innocuous.

Can you make the comments look like this and squash the commits?

```yml
"1f595": ["insult"] # middle finger
"1F4A9": ["inappropriate"] # poo
```

**Comment by m1foley** [comment]
The code looks perfect -- can you squash your commits into 1 commit so I can accept this PR?

**Comment by m1foley** [comment]
It looks like `lib/swearjar.rb` was accidentally changed, and the commits still need to be squashed into 1 commit. Would you like some help with the Git commands?

**Comment by suyesh** [comment]
Yes. What I tried to recommit and then I noticed the white spaces that I
didn't add at all. Looks normal on my machine but then when I pushed it
showed I changed a whole lot. Confused on what happened.

**Comment by m1foley** [comment]
I would suggest this:

- Run the command: `git rebase -i 6da45fc`. The "interactive rebase" file will open in your text editor.
- On the last line (`0acebc8`) change `pick` to `drop`.
- Aside from the first line (`6da45fc`) change every other `pick` to `squash`.
- Save & quit.

**Comment by suyesh** [comment]
I hope I did it correctly

**Comment by m1foley** [comment]
There are now 2 commits, so you need to squash it again into 1 commit. I think I made a mistake in the directions I gave you before.

1. `git rebase -i 86bcdb8`
2. Change the last `pick` to `squash`.
3. Write & save the commit message (maybe, "Add poo emoji")
4. `git push -f`

**Comment by suyesh** [comment]
Am i supposed to commit? i am lost in this haha. But i pushed it with the same message.

**Comment by m1foley** [comment]
Looks great. The commit message needs to be rewritten to be more succinct though. Just run `git commit --amend` to rewrite your most recent commit, and `git push -f` again.

**Comment by m1foley** [comment]
There's still a bunch of useless lines in that commit message ("Update en.yml" is repeated 3 times). Try it again and remove those superfluous lines.

**Comment by m1foley** [comment]
Since this hasn't been updated in a month, I will edit the commit message myself and preserve the authorship of the commit.

**Comment by m1foley** [comment]
Oops, I left this PR open for a while. This was fixed via cd1714a.

**Pull request closed without merging**
